/**
 * Standardized error codes across the application
 */

// Authentication errors
const AUTH_ERRORS = {
  NOT_AUTHENTICATED: "NOT_AUTHENTICATED",
  UNAUTHORIZED: "UNAUTHORIZED",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
} as const;

// Validation errors
const VALIDATION_ERRORS = {
  INVALID_INPUT: "INVALID_INPUT",
  MISSING_REQUIRED_FIELD: "MISSING_REQUIRED_FIELD",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  CHAT_NOT_FOUND: "CHAT_NOT_FOUND",
  MESSAGE_NOT_FOUND: "MESSAGE_NOT_FOUND",
  FILE_NOT_FOUND: "FILE_NOT_FOUND",
  CONNECTOR_NOT_FOUND: "CONNECTOR_NOT_FOUND",
} as const;

// Business logic errors
const BUSINESS_ERRORS = {
  PREMIUM_MODEL_ACCESS_DENIED: "PREMIUM_MODEL_ACCESS_DENIED",
  USER_KEY_REQUIRED: "USER_KEY_REQUIRED",
  UNSUPPORTED_MODEL: "UNSUPPORTED_MODEL",
  UNSUPPORTED_OPERATION: "UNSUPPORTED_OPERATION",
  REDACTED_CONTENT: "REDACTED_CONTENT",
} as const;

// File operation errors
const FILE_ERRORS = {
  UNSUPPORTED_FILE_TYPE: "UNSUPPORTED_FILE_TYPE",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  UPLOAD_FAILED: "UPLOAD_FAILED",
} as const;

const CONNECTOR_ERRORS = {
  CONNECTION_FAILED: "CONNECTION_FAILED",
  CONNECTION_NOT_FOUND: "CONNECTION_NOT_FOUND",
  CONNECTION_TIMEOUT: "CONNECTION_TIMEOUT",
  CONNECTOR_NOT_SUPPORTED: "CONNECTOR_NOT_SUPPORTED",
  CONNECTOR_AUTH_FAILED: "CONNECTOR_AUTH_FAILED",
} as const;

const STREAMING_ERRORS = {
  PROVIDER_STREAM_QUOTA_EXCEEDED: "PROVIDER_STREAM_QUOTA_EXCEEDED",
  PROVIDER_STREAM_INSUFFICIENT_BALANCE: "PROVIDER_STREAM_INSUFFICIENT_BALANCE",
  PROVIDER_STREAM_AUTH_ERROR: "PROVIDER_STREAM_AUTH_ERROR",
  PROVIDER_STREAM_TIMEOUT: "PROVIDER_STREAM_TIMEOUT",
  PROVIDER_STREAM_THROTTLED: "PROVIDER_STREAM_THROTTLED",
  PROVIDER_STREAM_RESOURCE_EXHAUSTED: "PROVIDER_STREAM_RESOURCE_EXHAUSTED",
  PROVIDER_CONTENT_POLICY_VIOLATION: "PROVIDER_CONTENT_POLICY_VIOLATION",
} as const;

// Combined error codes for easy import
export const ERROR_CODES = {
  ...AUTH_ERRORS,
  ...VALIDATION_ERRORS,
  ...BUSINESS_ERRORS,
  ...FILE_ERRORS,
  ...CONNECTOR_ERRORS,
  ...STREAMING_ERRORS,
} as const;
